### ISSUE TITLE
 fatal error: ../Browser/Layout/X3DLayoutContext.h: No such file or directory

### ISSUE THREAD

**Issue by popey** [create3000/titania#20]
I'm taking a look at fixing the snapcraft.yaml in the project. I'm building using "snapcraft cleanbuild" which builds in a xenial (16.04) lxd container. I had to make some changes to the yaml to account for there being no libjson-c3 in xenial. However, it crashes out (see below). Any ideas what I'm doing wrong?

### snapcraft.yaml
```
name: titania
version: 3.0.0
summary: Titania is a X3D/VRML editor and browser for Ubuntu.
description: Titania is a X3D/VRML editor and browser for Ubuntu.
confinement: strict

apps:
  titania:
    command: bin/titania-wrapper
    plugs: [network, network-bind, home, x11, unity7, gsettings]
  titania-bin:
    command: bin/titania
    plugs: [network, network-bind, home, x11, unity7, gsettings]

parts:
  libjson-c3:
    prepare: |
      autoreconf --force --install
    plugin: autotools
    source: https://github.com/json-c/json-c.git
    source-tag: 'json-c-0.12.1-20160607'
    build-packages:
      - gcc
  titania:
    after: [libjson-c3]
    plugin: autotools
    source: https://github.com/create3000/titania
    source-type: git
    build-packages:
      - libgtkmm-3.0-dev
      - libgtksourceviewmm-3.0-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - libglew-dev
      - libgl1-mesa-dev
      - libmozjs185-dev
      - libxml++2.6-dev
#      - libjson-c-dev
      - libfontconfig1-dev
      - libmagick++-dev
      - libcurl4-openssl-dev
      - libsqlite3-dev
      - libgstreamermm-1.0-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - zlib1g
      - intltool
      - gettext
      - libtool
      - libtool-bin
      - libgtop2-dev
      - libcgal-dev
      - libgmp-dev
      - libmpfr-dev
    stage-packages:
      - libgtkmm-3.0-1v5
      - libgtksourceviewmm-3.0-0v5
      - libglu1-mesa
      - libglew1.13
      - libgl1-mesa-glx
      - libmozjs185-1.0
      - libxml++2.6-2v5
#      - libjson-c3
      - libfontconfig1
      - libmagick++-6.q16-5v5
      - libcurl3
      - libsqlite3-0
      - libgstreamermm-1.0-0v5
      - zlib1g
      - libgtop-2.0-10
      - gettext
      - libcgal11v5
      - libgmp10
      - libmpfr4
      - ttf-ubuntu-font-family
      - language-pack-en
      - language-pack-de
      - libc-bin
  glue:
    plugin: copy
    files:
      titania-wrapper: bin/
 
```

### build snippet
```
  CXX      Titania/X3D/Browser/Notification.lo
  CXX      Titania/X3D/Browser/RenderingProperties.lo
  CXX      Titania/X3D/Browser/Selection.lo
  CXX      Titania/X3D/Browser/X3DBrowser.lo
In file included from Titania/X3D/Browser/../Browser/X3DBrowser.h:33:0,
                 from Titania/X3D/Browser/RenderingProperties.cpp:54:
Titania/X3D/Browser/../Browser/../Browser/X3DBrowserContext.h:64:48: fatal error: ../Browser/Layout/X3DLayoutContext.h: No such file or directory
compilation terminated.
In file included from Titania/X3D/Browser/X3DBrowser.h:33:0,
                 from Titania/X3D/Browser/X3DBrowser.cpp:51:
Titania/X3D/Browser/../Browser/X3DBrowserContext.h:64:48: fatal error: ../Browser/Layout/X3DLayoutContext.h: No such file or directory
compilation terminated.
Makefile:5480: recipe for target 'Titania/X3D/Browser/RenderingProperties.lo' failed
make[2]: *** [Titania/X3D/Browser/RenderingProperties.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:5480: recipe for target 'Titania/X3D/Browser/X3DBrowser.lo' failed
make[2]: *** [Titania/X3D/Browser/X3DBrowser.lo] Error 1
In file included from Titania/X3D/Browser/../Browser/X3DBrowser.h:33:0,
                 from Titania/X3D/Browser/Selection.cpp:54:
Titania/X3D/Browser/../Browser/../Browser/X3DBrowserContext.h:64:48: fatal error: ../Browser/Layout/X3DLayoutContext.h: No such file or directory
compilation terminated.
In file included from Titania/X3D/Browser/../Browser/X3DBrowser.h:33:0,
                 from Titania/X3D/Browser/Notification.cpp:55:
Titania/X3D/Browser/../Browser/../Browser/X3DBrowserContext.h:64:48: fatal error: ../Browser/Layout/X3DLayoutContext.h: No such file or directory
compilation terminated.
```
